name = "MyExample"
uuid = "d2df6250-d7b9-4a18-9e48-f7d68aec62a5"
authors = ["Jack Yang", "First Incorporate"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
